---

name: InstallApp

on: [push]

jobs:

  install:
    runs-on: self-hosted
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build cloudCtl
      run: make build-cloudctl

    - name: Generate Package
      run: make generate-app-package

    - name: Vet The Package - AppInspect
      env:
        SPLUNK_COM_USERNAME: ${{ secrets.SPLUNK_COM_USERNAME }}
        SPLUNK_COM_PASSWORD: ${{ secrets.SPLUNK_COM_PASSWORD }}
        STACK_NAME: ${{ secrets.STACK_NAME }}
      run: make inspect-app

    - uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: report.json
        path: report.json

    - name: Install The App On Stack - ACS
      env:
        SPLUNK_COM_USERNAME: ${{ secrets.SPLUNK_COM_USERNAME }}
        SPLUNK_COM_PASSWORD: ${{ secrets.SPLUNK_COM_PASSWORD }}
        STACK_TOKEN: ${{ secrets.VICTORIA_STACK_TOKEN }}
        STACK_NAME: ${{ secrets.VICTORIA_STACK_NAME }}
        ACS_URL: https://admin.splunk.com
      run: make install-app
